version: '3'
services:

    api:
      build: ./src
      container_name: "core-api"
      ports:
          - "8000:80"
      env_file:
          - ./src/.env
      volumes:
          # local:container
          - ./data/:/data
      depends_on:
          - postgres_db

    postgres_db:
      container_name: "sql-db"
      build:
          context: ./postgresSQL
          dockerfile: db.Dockerfile
      ports:
          - "5432:5432"
      restart: always
      volumes:
          - ./postgresdata:/var/lib/postgresql/data/
      environment:
          #- POSTGRES_USER=postgres
          #- POSTGRES_PASSWORD=test
          #- POSTGRES_USER=testApi
          - POSTGRES_USER=${PGUSER}
          - POSTGRES_PASSWORD=${PGPASSWORD}
          - POSTGRES_DB=${PGDATABASE}

volumes:
    api:
    postgres_data:


