version: '3'
services:

    api:
      build: ./src
      container_name: "core-api"
      ports:
          - "8000:80"
      volumes:
          # local:container
          - ./data/:/data
      depends_on:
          - postgres_db
      env_file:
          - ./.env

    postgres_db:
      container_name: "sql-db"
      build:
          context: ./postgresSQL
          dockerfile: db.Dockerfile
      ports:
          - "5432:5432"
      restart: always
      volumes:
          - ./postgresdata:/var/lib/postgresql/data/
      env_file:
          - ./.env
      environment:
        - POSTGRES_USER= "${PGUSER}"
        - POSTGRES_PASSWORD= "${PGPASSWORD}"
        - POSTGRES_DB= "${PGDATABASE}"
volumes:
    api:
    postgres_data:


